version: 2.1

jobs:
  build:
    docker:
      - image: hairyhenderson/gomplate-ci-build:latest
    working_directory: /src/go-codeowners
    steps:
      - checkout
      - run: go get -t -v
      - run: mkdir -p test-results
      - run:
          name: go test
          command: |
            trap "go-junit-report < /tmp/test-results/go-test.out > /tmp/test-results/report.xml" EXIT
            go test -v -race ./... | tee /tmp/test-results/go-test.out
      - store_test_results:
          path: /tmp/test-results

workflows:
  build:
    jobs:
      - build
